MDScreenManager:
    Screen:
        name: "main"
        id: main
        MDBackdrop:
            id: main-backdrop
            title: "Equapyzer"
            radius_left:  "25dp"
            radius_right: "25dp"
            header_text: ""
            MDBackdropFrontLayer:
                Front:
                    id: front
            MDBackdropBackLayer:
                Back:
                    id: back
    Screen:
        name: "create"
        id: create
        Create:













